modLoader="javafml"
loaderVersion="[26,)"
logoFile="dualwield.png"
[[mods]]
modId="dualwield"
version="1.0"
displayName="Dual Wield"
authors="DashMakes"
description='''Allows you dual wield weapons. Works on multiplayer.'''
[[dependencies.dualwield]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dualwield]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"